In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_true,y_predicted): #This is the big method
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print('Total error:',total_error)
    
    mae = total_error/len(y_true)
    print('MAE:',mae)
    return mae

In [3]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


np.float64(0.5)

In [4]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [5]:
np.mean(np.abs(y_predicted - y_true))#This is the short method

np.float64(0.5)

In [6]:
np.sum(np.abs(y_predicted - y_true))

np.float64(2.5)

In [7]:
np.log([0.000000000000000000000000000001])

array([-69.07755279])

In [9]:
epsilon = 1e-15

In [10]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [11]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [12]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [13]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [14]:
def log_loss(y_true,y_predicted): # Everything in one code
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [15]:
log_loss(y_true,y_predicted)

np.float64(17.2696280766844)